//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementBusStation.Models
{    
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.TicketSales = new HashSet<TicketSale>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeeAge { get; set; }
        public string EmployeePersonalIdNo { get; set; }
        public string EmployeeCountry { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeePhoneNumber { get; set; }
        public string EmployeeEmailAddress { get; set; }
        public string EmployeePassword { get; set; }
        public int EmployeeTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSale> TicketSales { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
    }
}