//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementBusStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketSale()
        {
            this.TicketSalesByBusLines = new HashSet<TicketSalesByBusLine>();
        }
    
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public int CustomerAge { get; set; }
        public string TicketNo { get; set; }
        public string Currency { get; set; }
        public decimal TicketPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalAmount { get; set; }       
        public DateTime CreatedDate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSalesByBusLine> TicketSalesByBusLines { get; set; }
    }
}