//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementBusStation.Models
{          
    public partial class TicketSalesByBusLine
    {
        public int Id { get; set; }
        public int TicketSaleId { get; set; }
        public int BusLineId { get; set; }
    
        public virtual BusLine BusLine { get; set; }
        public virtual TicketSale TicketSale { get; set; }
    }
}